---
title: "initial"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

# TODO

- térképen klaszterszám
- alap mutatók klaszterenként
- nuts vs time table -> klaszterszín


```{r}
library(tidyverse)
library(eurostat)
library(sf)

set.seed(2021)
```


## Data setup

```{r}
df_tfr <- get_eurostat("demo_r_find2", time_format = "num") %>% 
  filter(indic_de == "TOTFERRT") %>% 
  select(time, geo, tfr = values)

df_lifexp <- get_eurostat("demo_r_mlifexp", time_format = "num") %>% 
  filter(sex == "T" & age == "Y_LT1") %>% 
  select(time, geo, lifexp = values)
```

```{r}
df_ageing <- get_eurostat("demo_r_d2jan", time_format = "num") %>% 
  filter(age != "TOTAL" & age != "UNK" & sex == "T") %>% 
  mutate(
    age = ifelse(age == "Y_LT1", 0, age),
    age = ifelse(age == "Y_OPEN", 100, age),
    age = str_remove_all(age, "Y"),
    age = as.numeric(age),
    young = age <= 14
    ) %>% 
  filter(age <= 14 | age >= 65) %>% 
  group_by(time, geo, young) %>% 
  summarise(values = sum(values)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = young, values_from = values, names_prefix = "young") %>% 
  transmute(time, geo, ageing = youngFALSE / youngTRUE)

```

```{r}
df_motherrate <- get_eurostat("demo_r_d2jan", time_format = "num") %>% 
  filter(sex == "F" & age %in% c("TOTAL", str_c("Y", 15:49))) %>% 
  mutate(t = age == "TOTAL") %>% 
  group_by(time, geo, t) %>% 
  summarise(values = sum(values)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = t, values_from = values, names_prefix = "t") %>% 
  transmute(time, geo, motherrate = tFALSE / tTRUE)
```

```{r}
df_emp <- get_eurostat("lfst_r_lfe2emprtn", time_format = "num") %>% 
  filter(isced11 == "TOTAL" & citizen == "TOTAL" & age == "Y15-64" & sex == "F") %>% 
  select(time, geo, emp = values)
```

```{r}
dat <- list(df_tfr, df_lifexp, df_ageing, df_motherrate, df_emp) %>% 
  reduce(full_join) %>% 
  filter(str_length(geo) == 4 & geo != "HUXX") %>% 
  mutate(country = str_sub(str_sub(geo, end = 2))) %>% 
  filter(country %in% eu_countries$code) %>% 
  select(time, country, geo, everything())

dat
```

```{r}
dat <- dat %>% 
  select(-country) %>% 
  group_by(time) %>% 
  nest() %>% 
  mutate(
    data = map(data, na.omit),
    geo = map(data, "geo"),
    data = map(data, select, -geo),
    scaled_data = map(data, scale)
  )

dat
```

## Cluster analyses

```{r}
cluster_df <- crossing(time = 1999:2019, n_cluster = 2:10)

cluster_df
```

```{r}
cluster_df <- cluster_df %>% 
  mutate(
    fit = map2(time, n_cluster, 
               ~ kmeans(na.omit(filter(dat, time == .x)$scaled_data[[1]]), 
                        centers = .y, nstart=100, iter.max=100))
  )

cluster_df
```

```{r}
save(list = c("cluster_df", "dat"), file = "Cluster_result.RData")
```

