---
title: "initial"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(tidyverse)
library(eurostat)
library(sf)
```


## datasetup

```{r}
df_tfr <- get_eurostat("demo_r_find2", time_format = "num") %>% 
  filter(indic_de == "TOTFERRT") %>% 
  select(time, geo, tfr = values)

df_lifexp <- get_eurostat("demo_r_mlifexp", time_format = "num") %>% 
  filter(sex == "T" & age == "Y_LT1") %>% 
  select(time, geo, lifexp = values)
```

```{r}
df_ageing <- get_eurostat("demo_r_d2jan", time_format = "num") %>% 
  filter(age != "TOTAL" & age != "UNK" & sex == "T") %>% 
  mutate(
    age = ifelse(age == "Y_LT1", 0, age),
    age = ifelse(age == "Y_OPEN", 100, age),
    age = str_remove_all(age, "Y"),
    age = as.numeric(age),
    young = age <= 14
    ) %>% 
  filter(age <= 14 | age >= 65) %>% 
  group_by(time, geo, young) %>% 
  summarise(values = sum(values)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = young, values_from = values, names_prefix = "young") %>% 
  transmute(time, geo, ageing = youngFALSE / youngTRUE)

```

```{r}
df_motherrate <- get_eurostat("demo_r_d2jan", time_format = "num") %>% 
  filter(sex == "F" & age %in% c("TOTAL", str_c("Y", 15:49))) %>% 
  mutate(t = age == "TOTAL") %>% 
  group_by(time, geo, t) %>% 
  summarise(values = sum(values)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = t, values_from = values, names_prefix = "t") %>% 
  transmute(time, geo, motherrate = tFALSE / tTRUE)
```

```{r}
df_emp <- get_eurostat("lfst_r_lfe2emprtn", time_format = "num") %>% 
  filter(isced11 == "TOTAL" & citizen == "TOTAL" & age == "Y15-64" & sex == "F") %>% 
  select(time, geo, emp = values)
```

```{r}
dat <- list(df_tfr, df_lifexp, df_ageing, df_motherrate, df_emp) %>% 
  reduce(full_join) %>% 
  filter(str_length(geo) == 4 & geo != "HUXX") %>% 
  mutate(country = str_sub(str_sub(geo, end = 2))) %>% 
  filter(country %in% eu_countries$code) %>% 
  select(time, country, geo, everything())
```

## Cluster analyses

```{r}
count(dat, time) %>% 
  ggplot(aes(time, n)) + 
  geom_col()
```

```{r}
dat_scaled <- dat %>%
  na.omit() %>% 
  filter(time > 2005 & time < 2020) %>% 
  select(-(1:3)) %>% 
  scale()
```

```{r}
clusters_df <- dat %>%
  na.omit() %>% 
  filter(time >= 2005 & time < 2020) %>% 
  group_by(time) %>% 
  nest() %>% 
  mutate(
    obs = map_int(data, nrow),
    mdata = map(data, select_if, is.numeric),
    mdata = map(mdata, scale),
    silhuette_plot = map(mdata, ~ factoextra::fviz_nbclust(., FUNcluster = kmeans, method="silhouette") + ggtitle(time)),
    gap_stat_plot = map(mdata, ~ factoextra::fviz_nbclust(., FUNcluster = kmeans, method="gap_stat") + ggtitle(time))
  )
```

```{r fig.height=10}
clusters_df %>% 
  pull(silhuette_plot) %>% 
  rev() %>% 
  patchwork::wrap_plots(ncol = 3)
```


```{r fig.height=10}
clusters_df %>% 
  pull(gap_stat_plot) %>% 
  rev() %>% 
  patchwork::wrap_plots(ncol = 3)
```

```{r}
clusters_df <- clusters_df %>% 
  mutate(
    km3 = map(mdata, ~ kmeans(., centers = 3, nstart=100, iter.max=100)),
    km4 = map(mdata, ~ kmeans(., centers = 4, nstart=100, iter.max=100)),
    km5 = map(mdata, ~ kmeans(., centers = 5, nstart=100, iter.max=100))
  )
```


```{r}
clusters_df %>% 
  pivot_longer(km3:km5, names_to = "centers", values_to = "kmeans") %>% 
    transmute(time, centers = parse_number(centers), r_squared = map_dbl(kmeans, ~ .$betweenss / .$totss)) %>% 
  ggplot(aes(centers, time, fill = r_squared)) + 
  geom_tile(color = "black")
```

## dist matrix

```{r}
eurostat::get_eurostat_geospatial(nuts_level = "2") %>% 
  tibble() %>% 
  select(geo, geometry) %>% 
  mutate(
    c = sf::st_centroid(geometry),
    g = map(c, as.numeric),
    lng = map_dbl(g, 1),
    lat = map_dbl(g, 2)
         ) %>% 
  ggplot() + 
  geom_sf(aes(geometry = geometry)) +
  geom_point(aes(lng, lat), color = "red")
  
```

```{r}
eurostat::get_eurostat_geospatial(nuts_level = "2") %>% 
  tibble() %>% 
  select(geo, geometry) %>% 
  mutate(
    c = sf::st_centroid(geometry),
    g = map(c, as.numeric),
    lng = map_dbl(g, 1),
    lat = map_dbl(g, 2)
         ) %>% 
  select(geo, lng, lat) %>% 
  column_to_rownames("geo") %>% 
  dist(diag = T, upper = T)
```

